ktel/urls.py
from django.views.generic import RedirectView
from django.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('', include('patrasktel.urls')),
]

urlpatterns += [
    path('index', RedirectView.as_view(url='', permanent=True)),
]

patrasktel/urls.py
from django.urls import path
from . import views
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)
urlpatterns = [

]
urlpatterns = [
    path('', views.index, name='index'),
    path('routes/', views.route, name='routes'),
    path('announcements/', views.announcement, name='announcements'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('tickets/', views.tickets, name='tickets'),
]
handler404 = 'patrasktel.views.handler404'
handler500 = 'patrasktel.views.handler500'

patrasktel/models.py
from django.db import models

# Create your models here.


class Route(models.Model):
    """Model representing a Route"""
    name = models.CharField(
        max_length=200, help_text='''Enter the route's name''')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Ticket(models.Model):
    ZONE_CATEGORY = [
        ('A', 'Zone A'),
        ('B', 'Zone B'),
    ]
    PRICE_CATEGORY = [
        ('n', 'Normal Price'),
        ('r', 'Reduced Price'),
    ]
    source = models.CharField(
        max_length=150, help_text='''Enter the photo's source URL''',)
    zone = models.CharField(
        max_length=1, choices=ZONE_CATEGORY, default='A', help_text='''Enter A for local or B for intercity''',)
    price_cat = models.CharField(
        max_length=1, choices=PRICE_CATEGORY, default='n', help_text='''Enter Normal or Reduced''',)
    value = models.DecimalField(max_digits=5, decimal_places=2, blank=False, null=False, default='0.0',
                                help_text='''Enter the price of the ticket''',)
    customer = models.TextField(
        max_length=100, help_text='''Enter the eligible social categories''')

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.zone} {self.price_cat} {self.value} '


class Stop(models.Model):
    """Model representing a Stop"""
    ZONE_CATEGORY = [
        ('a', 'Zone A'),
        ('b', 'Zone B'),
    ]
    name = models.CharField(
        max_length=150, help_text='''Enter the stop's name''')

    zone = models.CharField(
        max_length=1, choices=ZONE_CATEGORY, default='a', help_text='''Enter A for local or B for intercity''',)
    number = models.IntegerField(
        help_text='''Which stop is it? E.g Fisrt Stop is number 1 etc''')
    route = models.ForeignKey('Route', default='1',
                              on_delete=models.CASCADE,
                              )

    class Meta:
        ordering = ['number']
        unique_together = ("route", "name")

    def getZone(self):
        '''Returns the zone the stop belongs to'''
        return self.zone

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Schedule(models.Model):
    '''Model representing the starting time of each route'''
    route = models.ForeignKey('Route', on_delete=models.CASCADE,)
    start_time = models.TimeField()

    class Meta:
        unique_together = ("route", "start_time")

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.route}, {self.start_time}'


class About(models.Model):
    source = models.CharField(
        max_length=150, help_text='''Enter the photo's source URL''',)

    text = models.TextField(
        max_length=2500, default="a", help_text='''Enter the main body of the announcement''')

    class Meta:
        ordering = ['-id']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} About'


class Contact(models.Model):
    phone = models.CharField(
        max_length=13, help_text='''Enter the company's phone number''',)
    email = models.EmailField(
        help_text='''Enter the company's phone number''',)

    address = models.CharField(
        max_length=100, help_text='''Enter the company's address''',)

    class Meta:
        ordering = ['-id']

    def get_url(self):
        return f'https://maps.google.com/maps?q={self.address}&t=&z=15&ie=UTF8&iwloc=&output=embed'

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.phone} {self.email} {self.address}'


class Announcement(models.Model):
    heading = models.CharField(
        max_length=200, help_text='''Enter the title of the announcement''')
    author = models.CharField(
        max_length=100, help_text='''Enter the author of the announcement''')
    date = models.DateTimeField()
    body = models.TextField(
        max_length=2000, help_text='''Enter the main body of the announcement''')

    class Meta:
        ordering = ['-date']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.heading} {self.date}'

patrasktel/views.py
from patrasktel.models import Route, Stop, Schedule, Announcement, Ticket, Contact, About
from django.shortcuts import render
from django.views import generic
# Create your views here.


def index(request):
    contact = Contact.objects.all().first()
    announcement = Announcement.objects.all().first()
    context = {
        'contact': contact,
        'announcement': announcement,
    }
    return render(request, 'index.html', context=context)


def announcement(request):
    announcement_list = Announcement.objects.all()
    contact = Contact.objects.all().first()
    context = {
        'announcement_list': announcement_list,
        'contact': contact,
    }
    return render(request, 'announcement_list.html', context=context)


def route(request):
    stops = Stop.objects.all()
    stop_list = []
    route_list = Route.objects.all()

    contact = Contact.objects.all().first()
    context = {
        'route_list': route_list,
        'stop_list': stop_list,
        'contact': contact,
    }
    return render(request, 'route_list.html', context=context)


def tickets(request):
    ATickets = Ticket.objects.filter(zone='A')
    an = ATickets.filter(price_cat='n').first()
    ar = ATickets.filter(price_cat='r').first()
    BTickets = Ticket.objects.filter(zone='B')
    bn = BTickets.filter(price_cat='n').first()
    br = BTickets.filter(price_cat='r').first()
    contact = Contact.objects.all().first()
    context = {
        'an': an,
        'ar': ar,
        'bn': bn,
        'br': br,
        'contact': contact,
    }
    return render(request, 'tickets.html', context=context)


def contact(request):
    contact = Contact.objects.all().first()
    context = {
        'contact': contact,
    }
    return render(request, 'contact.html', context=context)


def about(request):
    about = About.objects.all().first()
    contact = Contact.objects.all().first()
    context = {
        'about': about,
        'contact': contact,
    }
    return render(request, 'about.html', context=context)


def handler404(request, exception):
    return render(request, '404.html', status=404)


def handler500(request):
    return render(request, '500.html', status=500)

patrasktel/templates/about.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <h3> About us</h3>
    <div class="row">
        <div class="col-sm-4">
            <img class="img-thumbnail img-responsive" src="{{about.source}}" alt="Chania">
        </div>
        <div class="col-sm-8">
            <p>{{about.text}}</p>
        </div>
    </div>
</div>
{% endblock %}

{% block title %}<title>About us - Urban Bus</title>{% endblock %}

{% block topmenu %}
<li><a href="/">Home</a></li>
<li><a href="/routes">Routes</a></li>
<li><a href="/tickets">Tickets</a></li>
<li class="active"><a href="/about">About us</a></li>
<li><a href="/announcements">Announcements</a></li>
<li><a href="/contact">Contact us</a></li>
{% endblock %}

patrasktel/templates/announcement_list.html
{% extends "base_generic.html" %}

{% block content %}

<div class="container">
    <h3>Announcements</h3>

    <div class="row content">
        <div class="panel-group" id="accordion">

            {% for announcement in announcement_list %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title text-center">
                        <a data-toggle="collapse" data-parent="#accordion" href="#{{ announcement.pk }}anno">
                            {{announcement.heading}}</a>
                    </h2>
                    <p class="text-center small">{{announcement.date}}</p>
                </div>

                <div id="{{ announcement.pk }}anno" class="panel-collapse collapse">
                    <div class="panel-body">
                        <p class="text-center">{{announcement.body}}<br>{{announcement.author}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}



{% block topmenu %}
<li><a href="/">Home</a></li>
<li><a href="/routes">Routes</a></li>
<li><a href="/tickets">Tickets</a></li>
<li><a href="/about">About us</a></li>
<li class="active"><a href="/announcements">Announcements</a></li>
<li><a href="/contact">Contact us</a></li>
{% endblock %}
{% block title %}<title>Announcements - Urban Bus</title>{% endblock %}

patrasktel/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}{% endblock %}
    <meta charset="utf-8">
    <meta name="description" content="Assignment for GK802">
    <meta name="keywords" content="HTML,XHTML,CSS">
    <meta name="Author" content="George Ntoutsos">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <link rel="icon" type="image/png" sizes="192x192"
        href="https://raw.githubusercontent.com/gntouts/urbanBus/master/media/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32"
        href="https://raw.githubusercontent.com/gntouts/urbanBus/master/media/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96"
        href="https://raw.githubusercontent.com/gntouts/urbanBus/master/media/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16"
        href="https://raw.githubusercontent.com/gntouts/urbanBus/master/media/favicon-16x16.png">


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <style>
        body {
            padding-top: 5em;
        }

        footer {
            margin-top: 5em;
            padding-top: 1em;
            background-color: #222;
            color: rgb(255, 255, 255);
        }

        .card {
            margin: auto;
            margin-bottom: 2vw;
        }

        #topBtn {
            display: none;
            position: fixed;
            bottom: 20px;
            right: 30px;
            z-index: 99;
            outline: none;
            background-color: rgb(0, 0, 0);
            color: white;
            padding: 15px;
            border: none;
            border-radius: 4px;
        }
    </style>
</head>

<body>
    <!-- HEADER -->
    <nav class="navbar navbar-inverse navbar-fixed-top navbar-right">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="nav-link" href="/">
                    <img src="https://raw.githubusercontent.com/gntouts/urbanBus/master/media/logo-white.png"
                        width="200vw" alt="">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    {% block topmenu %}{% endblock %}
                </ul>

            </div>
        </div>
    </nav>
    <button type="button" class="btn btn-primary btn-dark btn-lg" onclick="topFunction()" id="topBtn"
        title="Go to top">Top</button>
    <!-- CONTENT -->


    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
    </div>

    <!-- FOOTER -->
    <footer class="page-footer">
        <div class="container-fluid">

            <div class="row">
                <div class="col-sm-4" style="padding-top: 0.5vw;">
                    <p class="text-center"><a class="link-unstyled" style="color:rgb(255, 255, 255);"
                            href="/routes">Routes</a></p>
                    <p class="text-center"><a class="link-unstyled" style="color:rgb(255, 255, 255);"
                            href="/tickets">Tickets</a></p>
                    <p class="text-center"><a class="link-unstyled" style="color:rgb(255, 255, 255);"
                            href="/">Homepage</a></p>
                </div>
                <div class="col-sm-4">
                    <ul class="list-unstyled">
                        <li><img src="https://raw.githubusercontent.com/gntouts/urbanBus/master/media/logo-footer.png"
                                class="img-rounded img-responsive" style="max-width: 10vw; margin: auto;" alt=""></li>

                    </ul>
                </div>
                <div class="col-sm-4" style="padding-top: 0.5vw;">
                    <p class="text-center"><i class="fas fa-map-marker-alt"
                            style="padding-right:1em; color:rgb(255, 255, 255);"></i><a
                            style="color:rgb(255, 255, 255);" href=" https://maps.google.com/maps?q={{contact.address}}"
                            target="_blank" rel="noopener noreferrer">{{contact.address}}</a></p>
                    <p class="text-center"><i class="fas fa-envelope"
                            style="padding-right:1em; color:rgb(255, 255, 255);"></i>
                        <a class="link-unstyled" style="color:rgb(255, 255, 255);" href="mailto:{{contact.email}}">
                            {{contact.email}}</a></p>
                    <p class="text-center"><i class="fas fa-phone" style="padding-right:1em;"></i><a
                            class="lik-unstyled" style="color:rgb(255, 255, 255);"
                            href="tel:{{contact.phone}}">{{contact.phone}}</a>
                    </p>
                </div>
            </div>
            <hr>
            <div class="row">
                <p class="text-center small" style="margin-top: 0; padding-top: 0; color:rgb(255, 255, 255);">© Made by
                    <a class="lik-unstyled" style="color:rgb(193, 227, 255);" href="https://github.com/gntouts"
                        target="_blank">me</a></p>
            </div>
        </div>


    </footer>
    <script>
        window.onscroll = function () {
            scrollFunction()
        };

        function scrollFunction() {
            if (document.body.scrollTop > 30 || document.documentElement.scrollTop > 30) {
                document.getElementById("topBtn").style.display = "block";
            } else {
                document.getElementById("topBtn").style.display = "none";
            }
        }

        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>
</body>

</html>

patrasktel/templates/contact.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <h3>Contact us</h3>
    <div class="row">

        <div class="col-sm-6" style="margin-bottom: 15vw;">
            <ul class="list-unstyled">
                <br><br>

                <li class="text-center">
                    <h4>Address</Address>:</h4>
                </li>
                <li class="text-center"><i class="fas fa-map-marker-alt"
                        style="padding-right:1em; color:rgb(0, 0, 0);"></i><strong>{{contact.address}}</strong>
                </li><br>
                <li class="text-center">
                    <h4>e-mail:</h4>
                </li>
                <li class="text-center"><i class="fas fa-envelope" style="padding-right:1em; color:rgb(0, 0, 0);"></i>
                    <a class="link-unstyled" style="color:rgb(0, 78, 102);" href="mailto:mail@urbanbus.gr">
                        <strong>{{contact.email}}</strong></a>
                </li>
                <br>
                <li class="text-center">
                    <h4>Phone:</h4>
                </li>
                <li class="text-center"><i class="fas fa-phone"
                        style="padding-right:1em;"></i><strong>{{contact.phone}}</strong>
                </li>
            </ul>
        </div>
        <div class="col-sm-6">
            <div class="map-responsive"><iframe width="450" height="450" src="{{contact.get_url}}" frameborder="0"
                    scrolling="no" marginheight="0" marginwidth="0"></iframe>
            </div>
            <style>
                .map-responsive {
                    overflow: hidden;
                    padding-bottom: 56.25%;
                    position: relative;
                    height: 0;
                }

                .map-responsive iframe {
                    left: 0;
                    top: 0;
                    height: 100%;
                    width: 100%;
                    position: absolute;
                }
            </style>
        </div>
    </div>
</div>
</div>

{% endblock %}

{% block title %}<title>Contact us - Urban Bus</title>{% endblock %}

{% block topmenu %}
<li><a href="/">Home</a></li>
<li><a href="/routes">Routes</a></li>
<li><a href="/tickets">Tickets</a></li>
<li><a href="/about">About us</a></li>
<li><a href="/announcements">Announcements</a></li>
<li class="active"><a href="/contact">Contact us</a></li>
{% endblock %}

patrasktel/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container-fluid">
    <div class="jumbotron jumbotron-fluid text-center" style="background-color:#333; color: white; padding: 0.5vw;">
        <h2>Patras' Bus</h2><br>
        <p>Welcome to Patras' Bus, the efficient and reliable choice for trasportation in Patras.</p>
    </div>
</div>

<div class="container text-center">
    <img src="https://urban-bus.netlify.com/media/logo-black.png" class="rounded mx-auto img"
        style="max-width: 40%; height: auto; margin-bottom: 3vh;" alt="Image Placeholder">
    <hr>
    <div class="row mx-auto">
        <div class=" col-sm-4">
            <div class="card text-center" style="width: 10vw;">
                <img style="width: 8vw;" class="card-img-top"
                    src="https://urban-bus.netlify.com/media/list-alt-solid.svg" alt="Card image cap">
                <div class="card-body text-center">
                    <h3 class="card-title">Routes</h3>
                    <p class="card-text">View details about route stops and timetables</p>
                    <a href="/routes" class="btn btn-primary" style="margin: auto;">Click here</a>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card text-center" style="width: 10vw;">
                <img class="card-img-top text-center" style="width: 10vw;"
                    src="https://urban-bus.netlify.com/media/ticket-alt-solid.svg" alt="ticket-icon">
                <div class="card-body text-center">
                    <h3 class="card-title">Tickets</h3>
                    <p class="card-text">View details about ticket prices
                    </p>
                    <a href="/tickets/" class="btn btn-primary" style="margin: auto;">Click here</a>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card text-center" style="width: 10vw;">
                <img style="width: 7.5vw;" class=" card-img-top text-center"
                    src="https://urban-bus.netlify.com/media/phone-square-solid.svg" alt="list-icon">
                <div class="card-body text-center">
                    <h3 class="card-title">Contact us</h3>
                    <p class="card-text">Contact us for further information
                    </p>
                    <a href="/contact" class="btn btn-primary" style="margin: auto;">Click here</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <hr>
    <div class="row content mx-auto text-center">

        <p class="h3">Latest announcement</p>
        <br>
        <div class="col-6">

            <p class="h4 text-center">

                {{announcement.heading}}
            </p>
            <p class="text-center small">{{announcement.date}}</p>
            <p class="h5 text-center" style="margin-bottom: 0.1vh;">{{announcement.body}}</p>
            <p class="h5 text-center" style="margin-bottom: 0.5vh;">-{{announcement.author}}</p>
            <hr>
            <a href="/announcements/" class="btn btn-primary" style="margin: auto; margin-bottom: 2vh;">View
                all</a>
        </div>


    </div>
</div>

</div>
</div>
</div>
<div class="col-3"></div>
</div>
{% endblock %}

{% block topmenu %}

<li class="active"><a href="/">Home</a></li>
<li><a href="/routes">Routes</a></li>
<li><a href="/tickets">Tickets</a></li>
<li><a href="/about">About us</a></li>
<li><a href="/announcements">Announcements</a></li>
<li><a href="/contact">Contact us</a></li>
{% endblock %}

{% block title %}<title>Urban Bus</title>{% endblock %}

patrasktel/templates/route_list.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container-fluid">
    <h3>Routes</h3>
    <hr>
    <div class="row content">
        <div class="panel-group" id="accordion">
            {% for route in route_list %}
            <p class="h4" style="padding-left: 0.8vw">{{ route.name }}</p>
            <div class="panel panel-default">
                <div class="panel-heading">

                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#{{ route.pk }}">
                            <strong>Stops</strong></a>
                    </h4>
                </div>
            </div>
            <div id="{{ route.pk }}" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <tr>
                                <th>Stop name</th>
                            </tr>
                            {% for stop in route.stop_set.all %}
                            <tr>
                                <td>
                                    <h4 style="display:inline">{{ stop.name}} </h5> <small>&nbsp&nbsp(Ζώνη:
                                            {{stop.zone|capfirst}})</small>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#{{ route.pk }}h">
                            <strong>Timetable</strong></a>
                    </h4>
                </div>
            </div>
            <div id="{{ route.pk }}h" class="panel-collapse collapse">
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <tr>
                                <th>Departure</th>
                            </tr>
                            {% for schedule in route.schedule_set.all %}
                            {% comment %} {% if stop.route == route.name %} {% endcomment %}
                            <tr>
                                <td>
                                    <h4 style="display:inline">{{ schedule.start_time}} </h4>
                                </td>
                            </tr>
                            {% comment %} {% endif %} {% endcomment %}
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}
{% block title %}<title>Routes - Urban Bus</title>{% endblock %}

{% block topmenu %}

<li><a href="/">Home</a></li>
<li class="active"><a href="/routes">Routes</a></li>
<li><a href="/tickets">Tickets</a></li>
<li><a href="/about">About us</a></li>
<li><a href="/announcements">Announcements</a></li>
<li><a href="/contact">Contact us</a></li>
{% endblock %}

patrasktel/templates/tickets.html
{% extends "base_generic.html" %}

{% block content %}
<div class="container">
    <h3> Tickets</h3>
    <div class="row text-center">
        <h2>Zone A</h2>
        <br>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="thumbnail">
                <img style="max-width: 15vw;" src="{{an.source}}" alt="green-ticket">
                <div class="caption text-center">
                    <h3>{{an.value}}€</h3>
                    <p>Ticket for routes in zone {{an.zone|capfirst}}</p>
                    <p><strong>Suitable for: {{an.customer}}</strong></p>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="thumbnail">
                <img style="max-width: 15vw;" src="{{ar.source}}" alt="blue-ticket">
                <div class="caption text-center">
                    <h3>{{ar.value}}€</h3>
                    <p>Ticket for routes in zone {{ar.zone|capfirst}}</p>
                    <p><strong>Suitable for: {{ar.customer}}</strong></p>
                </div>
            </div>
        </div>
    </div>

    <div class="row text-center">
        <h2>Zone B</h2>
        <br>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <div class="thumbnail">
                <img style="max-width: 15vw;" src="{{bn.source}}" alt="orange-ticket">
                <div class="caption text-center">
                    <h3>{{bn.value}}€</h3>
                    <p>Ticket for routes in zone {{bn.zone|capfirst}}</p>
                    <p><strong>Suitable for: {{bn.customer}}</strong></p>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="thumbnail">
                <img style="max-width: 15vw;" src="{{br.source}}" alt="brown-ticket">
                <div class="caption text-center">
                    <h3>{{br.value}}€</h3>
                    <p>Ticket for routes in zone {{br.zone|capfirst}}</p>
                    <p><strong>Suitable for: {{br.customer}}</strong></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}




{% block title %}<title>Tickets - Urban Bus</title>{% endblock %}

{% block topmenu %}
<li><a href="/">Home</a></li>
<li><a href="/routes">Routes</a></li>
<li class="active"><a href="/tickets">Tickets</a></li>
<li><a href="/about">About us</a></li>
<li><a href="/announcements">Announcements</a></li>
<li><a href="/contact">Contact us</a></li>
{% endblock %}